# AltNet discovery onion service (v3)
HiddenServiceDir /var/lib/tor/altnet-discovery
# HiddenServiceVersion 3   # можно вообще удалить — v3 по умолчанию
HiddenServicePort 80   127.0.0.1:8087
HiddenServicePort 4006 127.0.0.1:4006
